export const CATEGORIAS = [
    "Electrónica",
    "Ropa",
    "Hogar",
    "Deportes",
    "Juguetes",
    "Libros",
    "Mascotas",
    "Viveres y Abarrotes",
    "Tecnologia",
    "Perfumeria",
    "Comida Rapida",
    "Restaurante",
    "Belleza y cosmetologia",
    "Turismo",
    "Construccion",
    "Variedades",
    "Servicio Eléctrico",
    "Herreria",
    "Plomería",
    "Carpintería",
    "Obra Blanca",
    "Técnico en Refrigeración",
    "Otros",
    // Nuevas categorías sugeridas
    "Papelería",
    "Panadería",
    "Farmacia",
    "Ferretería",
    "Zapatería",
    "Jardinería",
    "Electrodomésticos",
    "Mueblería",
    "Bicicletería",
    "Tienda de Ropa Deportiva",
    "Tienda de Celulares",
    "Tienda de Regalos",
    "Tienda de Cosméticos",
    "Tienda de Accesorios",
    "Tienda de Juguetes",
    "Tienda de Computadoras",
    "Tienda de Videojuegos",
    "Tienda de Pinturas",
    "Tienda de Autoservicio",
    "Tienda de Licores",
    "Tienda de Alimentos Naturales"
];
