export const CATEGORIAS = [
    "Electrónica",
    "Ropa",
    "Hogar",
    "Deportes",
    "Juguetes",
    "Libros",
    "Mascotas",
    "viverres y Abarrotes",
    "Tecnologia",
    "Perfumeria",
    "Comida Rapida",
    "Restaurante",
    "Belleza y cosmetologia",
    "Turismo",
    "Construccion",
    "Variedades",
    "Servicio Eléctrico",
    "Herreria",
    "Plomería",
    "Carpintería",
    "Obra Blanca",
    "Técnico en Refrigeración"
    "Otros",
]; 
